spring:
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:3306/cloud_studio?useUnicode=true&characterEncoding=utf8
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: ${DB_USERNAME:root}
            password: ${DB_PASSWORD:}
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}

aliyun:
  oss:
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID:}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET:}
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    region: ${ALIYUN_OSS_REGION:cn-beijing}
